### ISSUE TITLE
Output HTML should be encoded in HTML5 and UTF-8

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/obp-access#5]
Right now the output looks like this:

<img width="945" alt="Screenshot 2024-04-08 at 15 58 48" src="https://github.com/metanorma/obp-access/assets/11865/ae2bd1cb-6e72-4f0b-b9e6-2b7f218568b8">

**Comment by ocvit** [comment]
https://github.com/metanorma/obp-access/pull/8 fixed this issue BTW

**Comment by ronaldtse** [comment]
@ocvit the page still looks like this and not using UTF-8 encoding.

<img width="1257" alt="Screenshot 2024-04-10 at 10 07 20" src="https://github.com/metanorma/obp-access/assets/11865/890e0a71-13f2-49e1-ae53-4e65d4891516">

**Comment by ocvit** [comment]
@ronaldtse I assume we're talking about [this page](https://www.iso.org/obp/ui#iso:std:iso:5598:ed-3:v1:en)?

Here's how it looks like for me:
<img width="1254" alt="Screenshot 2024-04-10 at 07 45 59" src="https://github.com/metanorma/obp-access/assets/13473505/72694535-5c58-41a5-afe7-f5ec15daf831">

And here is encoding of output HTML file:

```ruby
File.read('index.html').encoding
# => #<Encoding:UTF-8>
```
